[package]
name = "http_hello_world"
version = "0.0.1"
authors = ["Brennen Sprimont <brennen.j.sprimont@gmail.com>"]
edition = "2018"

[[bin]]
name = "http_hello_world"
path = "source/main.rs"

[dependencies]
time = "0.1"
log = "0.4.8"
env_logger = "0.7.1"
http = { path = "./../../" }
